language: node_js
node_js:
  - "12"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  local-dir: build
  repo: amazyyy/amazyyy.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: main
  target-branch: main
  name: Travis Helper
  email: teamamazyyy@gmail.com
